---
default:
  tags:
    - eks-mini

variables:
  VERSION: v1.0.9

stages:
  - build

build_image:
  stage: build
  image: docker:stable
  services:
    - name: docker:dind
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://127.0.0.1:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - 'docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}'
  script:
    - 'docker build -t ${CI_REGISTRY_IMAGE}:${VERSION} -f docker/Dockerfile.musl .'
    - 'docker push ${CI_REGISTRY_IMAGE}:${VERSION}'
...
